name: Latest AskDifferent activities
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-ask-different:
    name: Update this repo's README with latest activity from AskDifferent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "ASKDIFFERENT"
          commit_message: "Updated readme with the latest AskDifferent data"
          feed_names: "AskDifferent"
          feed_list: "https://apple.stackexchange.com/feeds/user/35986"
          # template: "$newline - $feedName: [$title]($url)"
          max_post_count: 5
